kind = "Viewlet"
name = "index"

output = "body-content"

[args]
key = "value"

[template]
name = "index-layout"
[template.layout]

height = "100vh"

[[template.layout.cols]]
name = "menu"
width = "180px,200px"

[[template.layout.cols]]
name = "body"
width = "auto"

[[next_viewlets]]
name = "nav-menu"
