// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.21.6
// source: uiapi.proto

package uiapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// frontend components
type Viewlet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind         string            `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Args         map[string]string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" toml:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Template     *TemplateSpec     `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty" toml:"template,omitempty"`
	Datalet      *DataletSpec      `protobuf:"bytes,7,opt,name=datalet,proto3" json:"datalet,omitempty" toml:"datalet,omitempty"`
	Output       string            `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty" toml:"output,omitempty"`
	NextViewlets []*Viewlet        `protobuf:"bytes,9,rep,name=next_viewlets,json=nextViewlets,proto3" json:"next_viewlets,omitempty" toml:"next_viewlets,omitempty"`
}

func (x *Viewlet) Reset() {
	*x = Viewlet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Viewlet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewlet) ProtoMessage() {}

func (x *Viewlet) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewlet.ProtoReflect.Descriptor instead.
func (*Viewlet) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{0}
}

func (x *Viewlet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Viewlet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Viewlet) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Viewlet) GetTemplate() *TemplateSpec {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Viewlet) GetDatalet() *DataletSpec {
	if x != nil {
		return x.Datalet
	}
	return nil
}

func (x *Viewlet) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Viewlet) GetNextViewlets() []*Viewlet {
	if x != nil {
		return x.NextViewlets
	}
	return nil
}

type TemplateSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string          `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Name   string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Layout *TemplateLayout `protobuf:"bytes,9,opt,name=layout,proto3" json:"layout,omitempty" toml:"layout,omitempty"`
	Nav    *TemplateNav    `protobuf:"bytes,10,opt,name=nav,proto3" json:"nav,omitempty" toml:"nav,omitempty"`
	Table  *TemplateTable  `protobuf:"bytes,11,opt,name=table,proto3" json:"table,omitempty" toml:"table,omitempty"`
	Html   *TemplateHtml   `protobuf:"bytes,31,opt,name=html,proto3" json:"html,omitempty" toml:"html,omitempty"`
}

func (x *TemplateSpec) Reset() {
	*x = TemplateSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSpec) ProtoMessage() {}

func (x *TemplateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSpec.ProtoReflect.Descriptor instead.
func (*TemplateSpec) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TemplateSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateSpec) GetLayout() *TemplateLayout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *TemplateSpec) GetNav() *TemplateNav {
	if x != nil {
		return x.Nav
	}
	return nil
}

func (x *TemplateSpec) GetTable() *TemplateTable {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *TemplateSpec) GetHtml() *TemplateHtml {
	if x != nil {
		return x.Html
	}
	return nil
}

type TemplateLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Align   string            `protobuf:"bytes,3,opt,name=align,proto3" json:"align,omitempty" toml:"align,omitempty"`
	Width   string            `protobuf:"bytes,4,opt,name=width,proto3" json:"width,omitempty" toml:"width,omitempty"`
	Height  string            `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty" toml:"height,omitempty"`
	Options map[string]string `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Rows    []*TemplateLayout `protobuf:"bytes,14,rep,name=rows,proto3" json:"rows,omitempty" toml:"rows,omitempty"`
	Cols    []*TemplateLayout `protobuf:"bytes,15,rep,name=cols,proto3" json:"cols,omitempty" toml:"cols,omitempty"`
}

func (x *TemplateLayout) Reset() {
	*x = TemplateLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateLayout) ProtoMessage() {}

func (x *TemplateLayout) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateLayout.ProtoReflect.Descriptor instead.
func (*TemplateLayout) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateLayout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateLayout) GetAlign() string {
	if x != nil {
		return x.Align
	}
	return ""
}

func (x *TemplateLayout) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

func (x *TemplateLayout) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *TemplateLayout) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TemplateLayout) GetRows() []*TemplateLayout {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TemplateLayout) GetCols() []*TemplateLayout {
	if x != nil {
		return x.Cols
	}
	return nil
}

type TemplateNav struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Display string              `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty" toml:"display,omitempty"`
	Item    []*TemplateNav_Item `protobuf:"bytes,9,rep,name=item,proto3" json:"item,omitempty" toml:"item,omitempty"`
}

func (x *TemplateNav) Reset() {
	*x = TemplateNav{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateNav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateNav) ProtoMessage() {}

func (x *TemplateNav) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateNav.ProtoReflect.Descriptor instead.
func (*TemplateNav) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateNav) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *TemplateNav) GetItem() []*TemplateNav_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type TemplateHtml struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty" toml:"file,omitempty"`
	Html string `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty" toml:"html,omitempty"`
}

func (x *TemplateHtml) Reset() {
	*x = TemplateHtml{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateHtml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateHtml) ProtoMessage() {}

func (x *TemplateHtml) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateHtml.ProtoReflect.Descriptor instead.
func (*TemplateHtml) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateHtml) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *TemplateHtml) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type TemplateTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TemplateTable) Reset() {
	*x = TemplateTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateTable) ProtoMessage() {}

func (x *TemplateTable) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateTable.ProtoReflect.Descriptor instead.
func (*TemplateTable) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{5}
}

type TemplateNav_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty" toml:"title,omitempty"`
}

func (x *TemplateNav_Item) Reset() {
	*x = TemplateNav_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateNav_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateNav_Item) ProtoMessage() {}

func (x *TemplateNav_Item) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateNav_Item.ProtoReflect.Descriptor instead.
func (*TemplateNav_Item) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TemplateNav_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateNav_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_uiapi_proto protoreflect.FileDescriptor

var file_uiapi_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x1a, 0x10, 0x75,
	0x69, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe8, 0x02, 0x0a, 0x07, 0x56, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61,
	0x70, 0x69, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x2e, 0x41, 0x72, 0x67, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67,
	0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x76, 0x69, 0x65, 0x77,
	0x6c, 0x65, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x6c, 0x65, 0x74, 0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x56, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74,
	0x73, 0x1a, 0x37, 0x0a, 0x09, 0x41, 0x72, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x84, 0x02, 0x0a, 0x0c, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75,
	0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x6e,
	0x61, 0x76, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x4e, 0x61, 0x76, 0x52, 0x03, 0x6e, 0x61, 0x76, 0x12, 0x33, 0x0a, 0x05, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x30, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x52, 0x04, 0x68, 0x74, 0x6d,
	0x6c, 0x22, 0xd3, 0x02, 0x0a, 0x0e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x67,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x67, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x45, 0x0a, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18,
	0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67,
	0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x12, 0x34, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x30, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d,
	0x6c, 0x22, 0x0f, 0x0a, 0x0d, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x42, 0x0c, 0x48, 0x03, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x75, 0x69, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uiapi_proto_rawDescOnce sync.Once
	file_uiapi_proto_rawDescData = file_uiapi_proto_rawDesc
)

func file_uiapi_proto_rawDescGZIP() []byte {
	file_uiapi_proto_rawDescOnce.Do(func() {
		file_uiapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_uiapi_proto_rawDescData)
	})
	return file_uiapi_proto_rawDescData
}

var file_uiapi_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_uiapi_proto_goTypes = []interface{}{
	(*Viewlet)(nil),          // 0: valuedig.uiapi.Viewlet
	(*TemplateSpec)(nil),     // 1: valuedig.uiapi.TemplateSpec
	(*TemplateLayout)(nil),   // 2: valuedig.uiapi.TemplateLayout
	(*TemplateNav)(nil),      // 3: valuedig.uiapi.TemplateNav
	(*TemplateHtml)(nil),     // 4: valuedig.uiapi.TemplateHtml
	(*TemplateTable)(nil),    // 5: valuedig.uiapi.TemplateTable
	nil,                      // 6: valuedig.uiapi.Viewlet.ArgsEntry
	nil,                      // 7: valuedig.uiapi.TemplateLayout.OptionsEntry
	(*TemplateNav_Item)(nil), // 8: valuedig.uiapi.TemplateNav.Item
	(*DataletSpec)(nil),      // 9: valuedig.uiapi.DataletSpec
}
var file_uiapi_proto_depIdxs = []int32{
	6,  // 0: valuedig.uiapi.Viewlet.args:type_name -> valuedig.uiapi.Viewlet.ArgsEntry
	1,  // 1: valuedig.uiapi.Viewlet.template:type_name -> valuedig.uiapi.TemplateSpec
	9,  // 2: valuedig.uiapi.Viewlet.datalet:type_name -> valuedig.uiapi.DataletSpec
	0,  // 3: valuedig.uiapi.Viewlet.next_viewlets:type_name -> valuedig.uiapi.Viewlet
	2,  // 4: valuedig.uiapi.TemplateSpec.layout:type_name -> valuedig.uiapi.TemplateLayout
	3,  // 5: valuedig.uiapi.TemplateSpec.nav:type_name -> valuedig.uiapi.TemplateNav
	5,  // 6: valuedig.uiapi.TemplateSpec.table:type_name -> valuedig.uiapi.TemplateTable
	4,  // 7: valuedig.uiapi.TemplateSpec.html:type_name -> valuedig.uiapi.TemplateHtml
	7,  // 8: valuedig.uiapi.TemplateLayout.options:type_name -> valuedig.uiapi.TemplateLayout.OptionsEntry
	2,  // 9: valuedig.uiapi.TemplateLayout.rows:type_name -> valuedig.uiapi.TemplateLayout
	2,  // 10: valuedig.uiapi.TemplateLayout.cols:type_name -> valuedig.uiapi.TemplateLayout
	8,  // 11: valuedig.uiapi.TemplateNav.item:type_name -> valuedig.uiapi.TemplateNav.Item
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_uiapi_proto_init() }
func file_uiapi_proto_init() {
	if File_uiapi_proto != nil {
		return
	}
	file_uiapi_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_uiapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Viewlet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateNav); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateHtml); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateNav_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uiapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uiapi_proto_goTypes,
		DependencyIndexes: file_uiapi_proto_depIdxs,
		MessageInfos:      file_uiapi_proto_msgTypes,
	}.Build()
	File_uiapi_proto = out.File
	file_uiapi_proto_rawDesc = nil
	file_uiapi_proto_goTypes = nil
	file_uiapi_proto_depIdxs = nil
}
