// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.21.6
// source: uiapi.proto

package uiapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelSpec_FieldType int32

const (
	ModelSpec_UNSPEC ModelSpec_FieldType = 0
	ModelSpec_BOOL   ModelSpec_FieldType = 1
	ModelSpec_INT    ModelSpec_FieldType = 2
	ModelSpec_UINT   ModelSpec_FieldType = 3
	ModelSpec_FLOAT  ModelSpec_FieldType = 4
	ModelSpec_STRING ModelSpec_FieldType = 6
	ModelSpec_BYTES  ModelSpec_FieldType = 7 // Encoded as a base64-encoded `string`
	ModelSpec_ARRAY  ModelSpec_FieldType = 8
	ModelSpec_JSON   ModelSpec_FieldType = 11 // Encoded as a JSON-formatted `string`
)

// Enum value maps for ModelSpec_FieldType.
var (
	ModelSpec_FieldType_name = map[int32]string{
		0:  "UNSPEC",
		1:  "BOOL",
		2:  "INT",
		3:  "UINT",
		4:  "FLOAT",
		6:  "STRING",
		7:  "BYTES",
		8:  "ARRAY",
		11: "JSON",
	}
	ModelSpec_FieldType_value = map[string]int32{
		"UNSPEC": 0,
		"BOOL":   1,
		"INT":    2,
		"UINT":   3,
		"FLOAT":  4,
		"STRING": 6,
		"BYTES":  7,
		"ARRAY":  8,
		"JSON":   11,
	}
)

func (x ModelSpec_FieldType) Enum() *ModelSpec_FieldType {
	p := new(ModelSpec_FieldType)
	*p = x
	return p
}

func (x ModelSpec_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelSpec_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_uiapi_proto_enumTypes[0].Descriptor()
}

func (ModelSpec_FieldType) Type() protoreflect.EnumType {
	return &file_uiapi_proto_enumTypes[0]
}

func (x ModelSpec_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelSpec_FieldType.Descriptor instead.
func (ModelSpec_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{5, 0}
}

// frontend components
type Viewlet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind         string            `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Args         map[string]string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" toml:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Template     *TemplateSpec     `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty" toml:"template,omitempty"`
	Datalet      *DataletSpec      `protobuf:"bytes,7,opt,name=datalet,proto3" json:"datalet,omitempty" toml:"datalet,omitempty"`
	Output       string            `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty" toml:"output,omitempty"`
	NextViewlets []*Viewlet        `protobuf:"bytes,9,rep,name=next_viewlets,json=nextViewlets,proto3" json:"next_viewlets,omitempty" toml:"next_viewlets,omitempty"`
}

func (x *Viewlet) Reset() {
	*x = Viewlet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Viewlet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewlet) ProtoMessage() {}

func (x *Viewlet) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewlet.ProtoReflect.Descriptor instead.
func (*Viewlet) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{0}
}

func (x *Viewlet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Viewlet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Viewlet) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Viewlet) GetTemplate() *TemplateSpec {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Viewlet) GetDatalet() *DataletSpec {
	if x != nil {
		return x.Datalet
	}
	return nil
}

func (x *Viewlet) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Viewlet) GetNextViewlets() []*Viewlet {
	if x != nil {
		return x.NextViewlets
	}
	return nil
}

type TemplateSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string          `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Name   string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Layout *TemplateLayout `protobuf:"bytes,9,opt,name=layout,proto3" json:"layout,omitempty" toml:"layout,omitempty"`
	Nav    *TemplateNav    `protobuf:"bytes,10,opt,name=nav,proto3" json:"nav,omitempty" toml:"nav,omitempty"`
	Html   *TemplateHtml   `protobuf:"bytes,31,opt,name=html,proto3" json:"html,omitempty" toml:"html,omitempty"`
}

func (x *TemplateSpec) Reset() {
	*x = TemplateSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSpec) ProtoMessage() {}

func (x *TemplateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSpec.ProtoReflect.Descriptor instead.
func (*TemplateSpec) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TemplateSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateSpec) GetLayout() *TemplateLayout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *TemplateSpec) GetNav() *TemplateNav {
	if x != nil {
		return x.Nav
	}
	return nil
}

func (x *TemplateSpec) GetHtml() *TemplateHtml {
	if x != nil {
		return x.Html
	}
	return nil
}

type TemplateLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Align   string            `protobuf:"bytes,3,opt,name=align,proto3" json:"align,omitempty" toml:"align,omitempty"`
	Width   string            `protobuf:"bytes,4,opt,name=width,proto3" json:"width,omitempty" toml:"width,omitempty"`
	Height  string            `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty" toml:"height,omitempty"`
	Options map[string]string `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Rows    []*TemplateLayout `protobuf:"bytes,14,rep,name=rows,proto3" json:"rows,omitempty" toml:"rows,omitempty"`
	Cols    []*TemplateLayout `protobuf:"bytes,15,rep,name=cols,proto3" json:"cols,omitempty" toml:"cols,omitempty"`
}

func (x *TemplateLayout) Reset() {
	*x = TemplateLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateLayout) ProtoMessage() {}

func (x *TemplateLayout) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateLayout.ProtoReflect.Descriptor instead.
func (*TemplateLayout) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateLayout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateLayout) GetAlign() string {
	if x != nil {
		return x.Align
	}
	return ""
}

func (x *TemplateLayout) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

func (x *TemplateLayout) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *TemplateLayout) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TemplateLayout) GetRows() []*TemplateLayout {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TemplateLayout) GetCols() []*TemplateLayout {
	if x != nil {
		return x.Cols
	}
	return nil
}

type TemplateNav struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Display string              `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty" toml:"display,omitempty"`
	Item    []*TemplateNav_Item `protobuf:"bytes,9,rep,name=item,proto3" json:"item,omitempty" toml:"item,omitempty"`
}

func (x *TemplateNav) Reset() {
	*x = TemplateNav{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateNav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateNav) ProtoMessage() {}

func (x *TemplateNav) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateNav.ProtoReflect.Descriptor instead.
func (*TemplateNav) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateNav) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *TemplateNav) GetItem() []*TemplateNav_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type TemplateHtml struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty" toml:"file,omitempty"`
	Html string `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty" toml:"html,omitempty"`
}

func (x *TemplateHtml) Reset() {
	*x = TemplateHtml{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateHtml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateHtml) ProtoMessage() {}

func (x *TemplateHtml) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateHtml.ProtoReflect.Descriptor instead.
func (*TemplateHtml) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateHtml) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *TemplateHtml) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

// backend components
type ModelSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind        string             `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Version     string             `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty" toml:"version,omitempty"`
	Name        string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Description string             `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" toml:"description,omitempty"`
	Fields      []*ModelSpec_Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty"`
	DefaultRows []*ModelSpec_Row   `protobuf:"bytes,9,rep,name=default_rows,json=defaultRows,proto3" json:"default_rows,omitempty" toml:"default_rows,omitempty"`
}

func (x *ModelSpec) Reset() {
	*x = ModelSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec) ProtoMessage() {}

func (x *ModelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec.ProtoReflect.Descriptor instead.
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{5}
}

func (x *ModelSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ModelSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelSpec) GetFields() []*ModelSpec_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ModelSpec) GetDefaultRows() []*ModelSpec_Row {
	if x != nil {
		return x.DefaultRows
	}
	return nil
}

type DataResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Spec *ModelSpec       `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty" toml:"spec,omitempty"`
	Rows []*ModelSpec_Row `protobuf:"bytes,9,rep,name=rows,proto3" json:"rows,omitempty" toml:"rows,omitempty"`
}

func (x *DataResult) Reset() {
	*x = DataResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResult) ProtoMessage() {}

func (x *DataResult) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResult.ProtoReflect.Descriptor instead.
func (*DataResult) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{6}
}

func (x *DataResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataResult) GetSpec() *ModelSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DataResult) GetRows() []*ModelSpec_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type DataRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model   string             `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty" toml:"model,omitempty"`
	Fields  []string           `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty"`
	Filters []*DataRead_Filter `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" toml:"filters,omitempty"`
	Limit   uint32             `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty" toml:"limit,omitempty"`
}

func (x *DataRead) Reset() {
	*x = DataRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRead) ProtoMessage() {}

func (x *DataRead) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRead.ProtoReflect.Descriptor instead.
func (*DataRead) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{7}
}

func (x *DataRead) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DataRead) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataRead) GetFilters() []*DataRead_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *DataRead) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DataWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model   string              `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty" toml:"model,omitempty"`
	Fields  []string            `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty"`
	Values  []string            `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty"`
	Filters []*DataWrite_Filter `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" toml:"filters,omitempty"`
}

func (x *DataWrite) Reset() {
	*x = DataWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataWrite) ProtoMessage() {}

func (x *DataWrite) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataWrite.ProtoReflect.Descriptor instead.
func (*DataWrite) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{8}
}

func (x *DataWrite) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DataWrite) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DataWrite) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DataWrite) GetFilters() []*DataWrite_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type DataAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string name = 1;
	Search *DataRead  `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty" toml:"search,omitempty"`
	Insert *DataWrite `protobuf:"bytes,3,opt,name=insert,proto3" json:"insert,omitempty" toml:"insert,omitempty"`
	Update *DataWrite `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty" toml:"update,omitempty"`
	Upsert *DataWrite `protobuf:"bytes,5,opt,name=upsert,proto3" json:"upsert,omitempty" toml:"upsert,omitempty"`
	Delete *DataWrite `protobuf:"bytes,6,opt,name=delete,proto3" json:"delete,omitempty" toml:"delete,omitempty"`
}

func (x *DataAction) Reset() {
	*x = DataAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAction) ProtoMessage() {}

func (x *DataAction) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataAction.ProtoReflect.Descriptor instead.
func (*DataAction) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{9}
}

func (x *DataAction) GetSearch() *DataRead {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *DataAction) GetInsert() *DataWrite {
	if x != nil {
		return x.Insert
	}
	return nil
}

func (x *DataAction) GetUpdate() *DataWrite {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *DataAction) GetUpsert() *DataWrite {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *DataAction) GetDelete() *DataWrite {
	if x != nil {
		return x.Delete
	}
	return nil
}

type DataletSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string      `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Name   string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Action *DataAction `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty" toml:"action,omitempty"`
}

func (x *DataletSpec) Reset() {
	*x = DataletSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataletSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataletSpec) ProtoMessage() {}

func (x *DataletSpec) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataletSpec.ProtoReflect.Descriptor instead.
func (*DataletSpec) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{10}
}

func (x *DataletSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataletSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataletSpec) GetAction() *DataAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type DataletRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     string        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty"`
	Dataset  *DataResult   `protobuf:"bytes,8,opt,name=dataset,proto3" json:"dataset,omitempty" toml:"dataset,omitempty"`
	Datasets []*DataResult `protobuf:"bytes,9,rep,name=datasets,proto3" json:"datasets,omitempty" toml:"datasets,omitempty"`
}

func (x *DataletRunResponse) Reset() {
	*x = DataletRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataletRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataletRunResponse) ProtoMessage() {}

func (x *DataletRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataletRunResponse.ProtoReflect.Descriptor instead.
func (*DataletRunResponse) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{11}
}

func (x *DataletRunResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DataletRunResponse) GetDataset() *DataResult {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *DataletRunResponse) GetDatasets() []*DataResult {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type TemplateNav_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty" toml:"title,omitempty"`
}

func (x *TemplateNav_Item) Reset() {
	*x = TemplateNav_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateNav_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateNav_Item) ProtoMessage() {}

func (x *TemplateNav_Item) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateNav_Item.ProtoReflect.Descriptor instead.
func (*TemplateNav_Item) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{3, 0}
}

func (x *TemplateNav_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateNav_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ModelSpec_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Type         ModelSpec_FieldType `protobuf:"varint,2,opt,name=type,proto3,enum=valuedig.uiapi.ModelSpec_FieldType" json:"type,omitempty" toml:"type,omitempty"`
	DefaultValue string              `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty" toml:"default_value,omitempty"`
	Length       uint32              `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty" toml:"length,omitempty"`
}

func (x *ModelSpec_Field) Reset() {
	*x = ModelSpec_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSpec_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec_Field) ProtoMessage() {}

func (x *ModelSpec_Field) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec_Field.ProtoReflect.Descriptor instead.
func (*ModelSpec_Field) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ModelSpec_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelSpec_Field) GetType() ModelSpec_FieldType {
	if x != nil {
		return x.Type
	}
	return ModelSpec_UNSPEC
}

func (x *ModelSpec_Field) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ModelSpec_Field) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ModelSpec_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*ModelSpec_Field `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty"`
}

func (x *ModelSpec_Item) Reset() {
	*x = ModelSpec_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSpec_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec_Item) ProtoMessage() {}

func (x *ModelSpec_Item) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec_Item.ProtoReflect.Descriptor instead.
func (*ModelSpec_Item) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ModelSpec_Item) GetFields() []*ModelSpec_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ModelSpec_Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string                   `protobuf:"bytes,9,rep,name=values,proto3" json:"values,omitempty" toml:"values,omitempty"`
	Fields map[string]*structpb.Value `protobuf:"bytes,10,rep,name=fields,proto3" json:"fields,omitempty" toml:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ModelSpec_Row) Reset() {
	*x = ModelSpec_Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelSpec_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec_Row) ProtoMessage() {}

func (x *ModelSpec_Row) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec_Row.ProtoReflect.Descriptor instead.
func (*ModelSpec_Row) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{5, 2}
}

func (x *ModelSpec_Row) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ModelSpec_Row) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DataRead_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty"`
}

func (x *DataRead_Filter) Reset() {
	*x = DataRead_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRead_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRead_Filter) ProtoMessage() {}

func (x *DataRead_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRead_Filter.ProtoReflect.Descriptor instead.
func (*DataRead_Filter) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{7, 0}
}

func (x *DataRead_Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataRead_Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DataWrite_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty" toml:"value,omitempty"`
}

func (x *DataWrite_Filter) Reset() {
	*x = DataWrite_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uiapi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataWrite_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataWrite_Filter) ProtoMessage() {}

func (x *DataWrite_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_uiapi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataWrite_Filter.ProtoReflect.Descriptor instead.
func (*DataWrite_Filter) Descriptor() ([]byte, []int) {
	return file_uiapi_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DataWrite_Filter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataWrite_Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_uiapi_proto protoreflect.FileDescriptor

var file_uiapi_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x02, 0x0a, 0x07,
	0x56, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x2e, 0x41, 0x72, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x12, 0x35, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07,
	0x64, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x3c, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69,
	0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x52,
	0x0c, 0x6e, 0x65, 0x78, 0x74, 0x56, 0x69, 0x65, 0x77, 0x6c, 0x65, 0x74, 0x73, 0x1a, 0x37, 0x0a,
	0x09, 0x41, 0x72, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xcf, 0x01, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x36, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52,
	0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x2d, 0x0a, 0x03, 0x6e, 0x61, 0x76, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e,
	0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61,
	0x76, 0x52, 0x03, 0x6e, 0x61, 0x76, 0x12, 0x30, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x1f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e,
	0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x74,
	0x6d, 0x6c, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x22, 0xd3, 0x02, 0x0a, 0x0e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x6c, 0x69, 0x67, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x45, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e,
	0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x32,
	0x0a, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x04, 0x63, 0x6f,
	0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8f,
	0x01, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69,
	0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x4e, 0x61, 0x76, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x30,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0x36, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x74, 0x6d, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x22, 0xe2, 0x05, 0x0a, 0x09, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x6f, 0x77, 0x73, 0x1a, 0x91, 0x01, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x23, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x1a, 0x3f, 0x0a, 0x04, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x37, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0xb3, 0x01, 0x0a, 0x03, 0x52,
	0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x51, 0x0a,
	0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x6b, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f,
	0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x55, 0x49, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10,
	0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x12, 0x09, 0x0a,
	0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x52, 0x41,
	0x59, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x0b, 0x22, 0x82, 0x01,
	0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2d, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12,
	0x31, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x39, 0x0a,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x32,
	0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64,
	0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x1a, 0x32, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8a, 0x02, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67,
	0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x31, 0x0a, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64,
	0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a,
	0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x12, 0x31, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x06, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x22, 0x69, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x96,
	0x01, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x12,
	0x36, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x64, 0x69, 0x67, 0x2e, 0x75, 0x69, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x42, 0x0c, 0x48, 0x03, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x75, 0x69, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uiapi_proto_rawDescOnce sync.Once
	file_uiapi_proto_rawDescData = file_uiapi_proto_rawDesc
)

func file_uiapi_proto_rawDescGZIP() []byte {
	file_uiapi_proto_rawDescOnce.Do(func() {
		file_uiapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_uiapi_proto_rawDescData)
	})
	return file_uiapi_proto_rawDescData
}

var file_uiapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_uiapi_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_uiapi_proto_goTypes = []interface{}{
	(ModelSpec_FieldType)(0),   // 0: valuedig.uiapi.ModelSpec.FieldType
	(*Viewlet)(nil),            // 1: valuedig.uiapi.Viewlet
	(*TemplateSpec)(nil),       // 2: valuedig.uiapi.TemplateSpec
	(*TemplateLayout)(nil),     // 3: valuedig.uiapi.TemplateLayout
	(*TemplateNav)(nil),        // 4: valuedig.uiapi.TemplateNav
	(*TemplateHtml)(nil),       // 5: valuedig.uiapi.TemplateHtml
	(*ModelSpec)(nil),          // 6: valuedig.uiapi.ModelSpec
	(*DataResult)(nil),         // 7: valuedig.uiapi.DataResult
	(*DataRead)(nil),           // 8: valuedig.uiapi.DataRead
	(*DataWrite)(nil),          // 9: valuedig.uiapi.DataWrite
	(*DataAction)(nil),         // 10: valuedig.uiapi.DataAction
	(*DataletSpec)(nil),        // 11: valuedig.uiapi.DataletSpec
	(*DataletRunResponse)(nil), // 12: valuedig.uiapi.DataletRunResponse
	nil,                        // 13: valuedig.uiapi.Viewlet.ArgsEntry
	nil,                        // 14: valuedig.uiapi.TemplateLayout.OptionsEntry
	(*TemplateNav_Item)(nil),   // 15: valuedig.uiapi.TemplateNav.Item
	(*ModelSpec_Field)(nil),    // 16: valuedig.uiapi.ModelSpec.Field
	(*ModelSpec_Item)(nil),     // 17: valuedig.uiapi.ModelSpec.Item
	(*ModelSpec_Row)(nil),      // 18: valuedig.uiapi.ModelSpec.Row
	nil,                        // 19: valuedig.uiapi.ModelSpec.Row.FieldsEntry
	(*DataRead_Filter)(nil),    // 20: valuedig.uiapi.DataRead.Filter
	(*DataWrite_Filter)(nil),   // 21: valuedig.uiapi.DataWrite.Filter
	(*structpb.Value)(nil),     // 22: google.protobuf.Value
}
var file_uiapi_proto_depIdxs = []int32{
	13, // 0: valuedig.uiapi.Viewlet.args:type_name -> valuedig.uiapi.Viewlet.ArgsEntry
	2,  // 1: valuedig.uiapi.Viewlet.template:type_name -> valuedig.uiapi.TemplateSpec
	11, // 2: valuedig.uiapi.Viewlet.datalet:type_name -> valuedig.uiapi.DataletSpec
	1,  // 3: valuedig.uiapi.Viewlet.next_viewlets:type_name -> valuedig.uiapi.Viewlet
	3,  // 4: valuedig.uiapi.TemplateSpec.layout:type_name -> valuedig.uiapi.TemplateLayout
	4,  // 5: valuedig.uiapi.TemplateSpec.nav:type_name -> valuedig.uiapi.TemplateNav
	5,  // 6: valuedig.uiapi.TemplateSpec.html:type_name -> valuedig.uiapi.TemplateHtml
	14, // 7: valuedig.uiapi.TemplateLayout.options:type_name -> valuedig.uiapi.TemplateLayout.OptionsEntry
	3,  // 8: valuedig.uiapi.TemplateLayout.rows:type_name -> valuedig.uiapi.TemplateLayout
	3,  // 9: valuedig.uiapi.TemplateLayout.cols:type_name -> valuedig.uiapi.TemplateLayout
	15, // 10: valuedig.uiapi.TemplateNav.item:type_name -> valuedig.uiapi.TemplateNav.Item
	16, // 11: valuedig.uiapi.ModelSpec.fields:type_name -> valuedig.uiapi.ModelSpec.Field
	18, // 12: valuedig.uiapi.ModelSpec.default_rows:type_name -> valuedig.uiapi.ModelSpec.Row
	6,  // 13: valuedig.uiapi.DataResult.spec:type_name -> valuedig.uiapi.ModelSpec
	18, // 14: valuedig.uiapi.DataResult.rows:type_name -> valuedig.uiapi.ModelSpec.Row
	20, // 15: valuedig.uiapi.DataRead.filters:type_name -> valuedig.uiapi.DataRead.Filter
	21, // 16: valuedig.uiapi.DataWrite.filters:type_name -> valuedig.uiapi.DataWrite.Filter
	8,  // 17: valuedig.uiapi.DataAction.search:type_name -> valuedig.uiapi.DataRead
	9,  // 18: valuedig.uiapi.DataAction.insert:type_name -> valuedig.uiapi.DataWrite
	9,  // 19: valuedig.uiapi.DataAction.update:type_name -> valuedig.uiapi.DataWrite
	9,  // 20: valuedig.uiapi.DataAction.upsert:type_name -> valuedig.uiapi.DataWrite
	9,  // 21: valuedig.uiapi.DataAction.delete:type_name -> valuedig.uiapi.DataWrite
	10, // 22: valuedig.uiapi.DataletSpec.action:type_name -> valuedig.uiapi.DataAction
	7,  // 23: valuedig.uiapi.DataletRunResponse.dataset:type_name -> valuedig.uiapi.DataResult
	7,  // 24: valuedig.uiapi.DataletRunResponse.datasets:type_name -> valuedig.uiapi.DataResult
	0,  // 25: valuedig.uiapi.ModelSpec.Field.type:type_name -> valuedig.uiapi.ModelSpec.FieldType
	16, // 26: valuedig.uiapi.ModelSpec.Item.fields:type_name -> valuedig.uiapi.ModelSpec.Field
	19, // 27: valuedig.uiapi.ModelSpec.Row.fields:type_name -> valuedig.uiapi.ModelSpec.Row.FieldsEntry
	22, // 28: valuedig.uiapi.ModelSpec.Row.FieldsEntry.value:type_name -> google.protobuf.Value
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_uiapi_proto_init() }
func file_uiapi_proto_init() {
	if File_uiapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uiapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Viewlet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateNav); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateHtml); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataletSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataletRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateNav_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSpec_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSpec_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelSpec_Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRead_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uiapi_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataWrite_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uiapi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uiapi_proto_goTypes,
		DependencyIndexes: file_uiapi_proto_depIdxs,
		EnumInfos:         file_uiapi_proto_enumTypes,
		MessageInfos:      file_uiapi_proto_msgTypes,
	}.Build()
	File_uiapi_proto = out.File
	file_uiapi_proto_rawDesc = nil
	file_uiapi_proto_goTypes = nil
	file_uiapi_proto_depIdxs = nil
}
